# Generated by Django 4.2.20 on 2025-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210921_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='ke_price',
            field=models.IntegerField(null=True),
        ),
    ]
