# Generated by Django 4.2.20 on 2025-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_subplan_ke_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='ke_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
